# Generated by Django 2.2.10 on 2020-03-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superior',
            options={'ordering': ['id'], 'verbose_name': '工作人员', 'verbose_name_plural': '工作人员'},
        ),
        migrations.AlterField(
            model_name='belongto',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='bought_date',
            field=models.DateField(blank=True, null=True, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='汽车品牌'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='汽车型号'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='车牌'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='购买价格/万'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_info_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_info_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=255, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Superior', verbose_name='客户归属'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_related_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='保险出单公司'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BelongTo', verbose_name='归属渠道'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CarInfo', verbose_name='车辆信息'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_record_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_record_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.InsuranceCompany', verbose_name='保险公司'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='insurance_date',
            field=models.DateField(blank=True, null=True, verbose_name='保单开始日期'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='is_payed',
            field=models.BooleanField(default=True, verbose_name='已支付'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='payback_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='已返金额'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='payback_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='已返费率'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Superior', verbose_name='验车人'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='record_date',
            field=models.DateField(null=True, verbose_name='签单日期'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='车船税'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='含税总保费'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superior_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superior_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='等级描述'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level_code',
            field=models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='等级编号'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='等级名称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='current_credits',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='当前积分'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='desc',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (0, '未知')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='是客户'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='是管理员'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='是合伙人'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UserLevel', verbose_name='用户等级'),
        ),
        migrations.CreateModel(
            name='ServiceReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_type', models.IntegerField(blank=True, choices=[(1, '上门'), (2, '到店')], null=True, verbose_name='预约类型')),
                ('reserve_time', models.DateTimeField(blank=True, null=True, verbose_name='预约时间')),
                ('reserve_address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='预约地点')),
                ('is_checked', models.BooleanField(default=False, verbose_name='已联系/已确认')),
                ('is_served', models.BooleanField(default=False, verbose_name='服务已完成')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CarInfo', verbose_name='车辆信息')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reserve_check_by', to='app.Superior', verbose_name='由谁联系')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reserve_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reserve_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reserve_served_by', to='app.Superior', verbose_name='由谁服务')),
            ],
            options={
                'verbose_name': '预约服务',
                'verbose_name_plural': '预约服务',
                'ordering': ['-id'],
            },
        ),
    ]
