# Generated by Django 2.2.10 on 2020-03-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200306_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name': '套餐归类',
                'verbose_name_plural': '套餐归类',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicereserve',
            options={'ordering': ['-id'], 'verbose_name': '服务预约', 'verbose_name_plural': '服务预约'},
        ),
        migrations.AddField(
            model_name='servicereserve',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='是预约服务'),
        ),
        migrations.AlterField(
            model_name='servicereserve',
            name='reserve_address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='服务地点'),
        ),
        migrations.AlterField(
            model_name='servicereserve',
            name='reserve_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='服务时间'),
        ),
        migrations.AlterField(
            model_name='servicereserve',
            name='reserve_type',
            field=models.IntegerField(blank=True, choices=[(1, '上门'), (2, '到店')], null=True, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='介绍')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServicePackageType', verbose_name='归类')),
            ],
            options={
                'verbose_name': '服务套餐',
                'verbose_name_plural': '服务套餐',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='servicereserve',
            name='service_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ServicePackage', verbose_name='服务套餐'),
        ),
    ]
