# Generated by Django 2.2.10 on 2020-03-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200312_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='oil_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.OilPackage', verbose_name='机油套餐'),
        ),
        migrations.AlterField(
            model_name='serviceapply',
            name='oil_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.OilPackage', verbose_name='机油套餐'),
        ),
        migrations.AlterField(
            model_name='serviceapply',
            name='service_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ServicePackage', verbose_name='服务套餐'),
        ),
    ]
