# Generated by Django 2.2.10 on 2020-03-14 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200313_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapply',
            name='money_needed',
            field=models.IntegerField(blank=True, null=True, verbose_name='需求金额/元'),
        ),
        migrations.AlterField(
            model_name='insuranceapply',
            name='insurance_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'display': True, 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_apply_check_by', to='app.InsuranceCompany', verbose_name='保险公司'),
        ),
        migrations.CreateModel(
            name='PartnerApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名字')),
                ('mobile', models.CharField(max_length=255, null=True, verbose_name='手机')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='长期居住地')),
                ('professional', models.CharField(blank=True, max_length=100, null=True, verbose_name='现就职业')),
                ('reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='申请理由或资源')),
                ('is_checked', models.BooleanField(default=False, verbose_name='已联系/已确认')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apply_check_by', to='app.Superior', verbose_name='由谁联系')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apply_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apply_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '城市合伙人',
                'verbose_name_plural': '城市合伙人',
                'ordering': ['-id'],
            },
        ),
    ]
