# Generated by Django 2.2.10 on 2020-03-20 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200314_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongto',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_to_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_to_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='记录时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='belongto',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_to_related_to', to='app.BelongTo', verbose_name='相同渠道'),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='ic_payback_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='返费金额'),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='ic_payback_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='保险公司返点'),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='profits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='利润'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='payback_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='已返费率'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='InsuranceRecordUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名')),
                ('total_count', models.IntegerField(blank=True, null=True, verbose_name='总条数')),
                ('created_count', models.IntegerField(blank=True, null=True, verbose_name='添加条数')),
                ('updated_count', models.IntegerField(blank=True, null=True, verbose_name='更新条数')),
                ('failed_count', models.IntegerField(blank=True, null=True, verbose_name='失败条数')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='已确认')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已执行')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_record_upload_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_record_upload_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '保险业绩数据导入',
                'verbose_name_plural': '保险业绩数据导入',
                'ordering': ['-id'],
            },
        ),
    ]
