# Generated by Django 2.2.10 on 2020-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200320_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackagetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_package_type', verbose_name='图片'),
        ),
    ]
