# Generated by Django 2.2.10 on 2020-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_insurancecompany_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapply',
            name='insurance_company',
            field=models.CharField(max_length=100, null=True, verbose_name='保险公司'),
        ),
    ]
