# Generated by Django 2.2.10 on 2020-03-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200323_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapply',
            name='service_type',
            field=models.IntegerField(blank=True, choices=[(1, '车辆续保'), (2, '保险分期'), (3, '购车贷款')], help_text='1-->车辆续保, 2-->保险分期, 3-->购车贷款', null=True, verbose_name='类别'),
        ),
    ]
