# Generated by Django 2.2.10 on 2020-03-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200324_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountchangerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creditchangerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wxuser',
            name='current_amounts',
        ),
        migrations.RemoveField(
            model_name='wxuser',
            name='current_credits',
        ),
        migrations.AddField(
            model_name='amountchangerecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='creditchangerecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_amounts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='请到[积分/余额-->余额变更]添加记录', max_digits=10, null=True, verbose_name='当前余额'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_credits',
            field=models.BigIntegerField(blank=True, default=0, help_text='请到[积分/余额-->积分变更]添加记录', null=True, verbose_name='当前积分'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='openid_gzh',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信公众号OpenID'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联账号'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信小程序OpenID'),
        ),
    ]
