# Generated by Django 2.2.10 on 2020-03-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200324_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxuser',
            options={'ordering': ['-id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
