# Generated by Django 2.2.10 on 2020-03-25 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200325_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, choices=[('归属统计', '归属统计')], max_length=255, null=True, verbose_name='报告类型')),
                ('file', models.FileField(blank=True, editable=False, null=True, upload_to='report', verbose_name='报告文件')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已执行')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_make_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_make_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '报告生成',
                'verbose_name_plural': '报告生成',
                'ordering': ['-id'],
            },
        ),
    ]
