# Generated by Django 2.2.10 on 2020-03-26 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_reportmake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='related_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='related_user',
            field=models.ManyToManyField(blank=True, related_name='customer_related_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
