# Generated by Django 2.2.10 on 2020-04-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200326_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='annual_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='车辆年检日期'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='保险公司'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='insurance_date',
            field=models.DateField(blank=True, null=True, verbose_name='交强险到期日'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计出厂时间'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总成本'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收金额'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收金额'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vehicle_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前行驶公里数'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='related_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.StoreInfo', verbose_name='维修门店'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='reserve_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进厂时间'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='reserve_type',
            field=models.IntegerField(blank=True, choices=[(1, '上门'), (2, '到店')], null=True, verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_record_served_by', to='app.Superior', verbose_name='维修人员'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_item_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_item_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
                ('related_service_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServiceRecord', verbose_name='维修服务')),
            ],
            options={
                'verbose_name': '维修项目',
                'verbose_name_plural': '维修项目',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(blank=True, null=True, verbose_name='回访日期')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_feedback_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_feedback_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
                ('feedback_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Superior', verbose_name='回访人员')),
                ('related_service_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ServiceRecord', verbose_name='维修服务')),
            ],
            options={
                'verbose_name': '回访记录',
                'verbose_name_plural': '回访记录',
                'ordering': ['-id'],
            },
        ),
    ]
