# Generated by Django 2.2.10 on 2020-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200401_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapply',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='首付/元'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='insurance_jqx',
            field=models.BooleanField(default=True, help_text='中国首个由国家法律规定实行的强制保险制度。其保费是实行全国统一收费标准的，由国家统一规定的，但是不同的汽车型号的交强险价格也不同，主要影响因素是“汽车座位数”', verbose_name='交强险'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='money_ccs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='车船税金额/元'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='money_jqx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='交强险金额/元'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='money_syx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='商业险金额/元'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='stage_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='每期/元'),
        ),
        migrations.AddField(
            model_name='insuranceapply',
            name='stages',
            field=models.IntegerField(blank=True, choices=[(3, 3), (6, 6), (9, 9)], null=True, verbose_name='分期数'),
        ),
        migrations.AddField(
            model_name='insurancerecord',
            name='insurance_jqx',
            field=models.BooleanField(default=True, help_text='中国首个由国家法律规定实行的强制保险制度。其保费是实行全国统一收费标准的，由国家统一规定的，但是不同的汽车型号的交强险价格也不同，主要影响因素是“汽车座位数”', verbose_name='交强险'),
        ),
    ]
