# Generated by Django 2.2.10 on 2020-04-07 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200403_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgSendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='验证码')),
                ('paras', models.CharField(blank=True, max_length=200, null=True, verbose_name='数据')),
                ('msg_type', models.IntegerField(choices=[(1, '验证码'), (2, '支付记录')], null=True, verbose_name='短信类型')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_send_record_confirmed_by', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_send_record_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '短信发送记录',
                'verbose_name_plural': '短信发送记录',
                'ordering': ['-id'],
            },
        ),
    ]
