# Generated by Django 2.2.10 on 2020-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200413_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payedrecord',
            name='total_payed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果是挂账，请填写0', max_digits=10, verbose_name='实收金额（元）'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='item_count',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='数量'),
        ),
    ]
