# Generated by Django 2.2.10 on 2020-04-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200413_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名字')),
                ('mobile', models.CharField(max_length=255, null=True, unique=True, verbose_name='手机')),
                ('related_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
            options={
                'verbose_name': '城市合伙人',
                'verbose_name_plural': '城市合伙人',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='insurancerecord',
            name='related_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Partner', verbose_name='城市合伙人'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='related_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Partner', verbose_name='城市合伙人'),
        ),
    ]
