# Generated by Django 2.2.10 on 2020-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200414_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='银行账户-姓名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='银行账户-卡号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='银行名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='请尽量填写真实姓名', max_length=255, null=True, verbose_name='名字'),
        ),
    ]
