# Generated by Django 2.2.10 on 2020-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200415_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='is_payed',
            field=models.BooleanField(default=False, help_text='若已支付，请勾选此项', verbose_name='已支付'),
        ),
    ]
