# Generated by Django 2.2.10 on 2020-04-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_servicerecord_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountchangerecord',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, '充值'), (2, '支付'), (3, '合伙人收益'), (4, '其他')], default=1, help_text='1-->充值, 2-->支付, 3-->合伙人收益, 4-->其他', verbose_name='变更类型'),
        ),
        migrations.AlterField(
            model_name='amountchangerecord',
            name='related_payed_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PayedRecord', verbose_name='关联收银记录'),
        ),
        migrations.AlterField(
            model_name='creditchangerecord',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, '消费获取'), (2, '活动获取'), (3, '支付抵扣'), (4, '其他')], default=1, help_text='1-->消费获取, 2-->活动获取, 3-->支付抵扣, 4-->其他', verbose_name='变更类型'),
        ),
        migrations.AlterField(
            model_name='creditchangerecord',
            name='related_payed_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PayedRecord', verbose_name='关联收银记录'),
        ),
        migrations.AlterField(
            model_name='payedrecord',
            name='related_insurance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.InsuranceRecord', verbose_name='关联保险'),
        ),
        migrations.AlterField(
            model_name='payedrecord',
            name='related_service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServiceRecord', verbose_name='关联服务'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='is_payed',
            field=models.BooleanField(default=False, help_text='勾选此项会自动创建收银记录', verbose_name='已支付'),
        ),
    ]
