# Generated by Django 2.2.10 on 2020-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200424_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='累计消费（元）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_consumption_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='累计消费-保险（元）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_consumption_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='累计消费-维修（元）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_credits',
            field=models.BigIntegerField(blank=True, default=0, help_text='历史获得的积分的综合', null=True, verbose_name='累计积分'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='month_mileage',
            field=models.IntegerField(help_text='未知可填写为0', null=True, verbose_name='月行驶公里数'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_amounts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='请到[收银台-->余额变更]添加记录', max_digits=10, null=True, verbose_name='当前余额（元）'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_credits',
            field=models.BigIntegerField(blank=True, default=0, help_text='请到[收银台-->积分变更]添加记录', null=True, verbose_name='当前积分'),
        ),
    ]
