# Generated by Django 2.2.10 on 2020-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200511_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_payed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='总已付款（元）'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='总应付款（元）'),
        ),
        migrations.AlterField(
            model_name='payedrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
