# Generated by Django 2.2.10 on 2020-06-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200521_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeedback',
            name='related_service_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ServiceRecord', verbose_name='维修服务'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='item_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='单价（元）'),
        ),
    ]
